version: '3.9'

services:
  db:
    restart: always
    image: postgres:14
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    expose:
      - "5432"
  django:
    restart: always
    build: ./django
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/app
