# Generated by Django 4.0.4 on 2022-04-17 19:31

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('sw_collections', '0002_alter_swdatacollection_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swdatacollection',
            name='data_file',
            field=models.FilePathField(path=pathlib.PurePosixPath('/opt/project/django')),
        ),
    ]
