# Generated by Django 4.0.4 on 2022-04-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_collections', '0003_alter_swdatacollection_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swdatacollection',
            name='data_file',
            field=models.FilePathField(path='/app/collections_data'),
        ),
    ]
